services:
  simulation:
    image: slam:testing_sim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulation
    privileged: true
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp #rmw_cyclonedds_cpp
    network_mode: host
    ipc: host
    stdin_open: true
    volumes:
      - /dev:/dev #for joystick
      - ./clearpath:/root/clearpath
    command: ros2 launch clearpath_gz simulation.launch.py setup_path:=/root/clearpath rviz:=true world:=myworld