services:
  turtlebot_sim:
    image: slam:testing_sim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turtlebot_sim
    privileged: true
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
    network_mode: host
    ipc: host
    stdin_open: true
    volumes:
      - /dev:/dev #for joystick
    command: 
      - bash
      - -c
      - |
          source /root/ros2_ws/install/setup.bash
          source /usr/share/gazebo/setup.bash
          ros2 launch /launch/sim.launch.py