teleop_twist_joy_node: #https://github.com/ros2/teleop_twist_joy/tree/humble
  ros__parameters:
    axis_linear:
      x: 1 #left joy stick vertical
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 3 #right joy stick horizontal
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    enable_button: 4 # Left top shoulder
    enable_turbo_button: 5 # right top shoulder
