services:
  .common:
    image: slam
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: build
    environment:
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
      DISPLAY: $DISPLAY
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp #rmw_cyclonedds_cpp
    network_mode: host
    ipc: host
    privileged: true #high security
    stdin_open: true

  .common_nvidia:
    extends: .common
    runtime: nvidia
    environment:
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics